import matplotlib.pyplot as plt
import networkx as nx

countries = ['AUS', 'BRA', 'CAN', 'CHN', 'DEU', 'ESP', 'FRA', 'GBR', 'HKG', 'ITA', 'JPN', 'KOR', 'MEX', 'MYS', 'NLD', 'SGP', 'USA']

G= nx.DiGraph()
for pais in countries:
    G.add_node(pais)

"""
ARISTAS DE RED RESIDUAL DE FLUJO MÁXIMO
"""
G.add_edge('AUS', 'USA')
G.add_edge('AUS', 'BRA')
G.add_edge('AUS', 'CAN')
G.add_edge('AUS', 'DEU')
G.add_edge('AUS', 'ESP')
G.add_edge('AUS', 'FRA')
G.add_edge('AUS', 'GBR')
G.add_edge('AUS', 'ITA')
G.add_edge('AUS', 'JPN')
G.add_edge('AUS', 'MEX')
G.add_edge('AUS', 'MYS')
G.add_edge('AUS', 'NLD')
G.add_edge('AUS', 'SGP')

G.add_edge('BRA', 'USA')
G.add_edge('BRA', 'CAN')
G.add_edge('BRA', 'GBR')
G.add_edge('BRA', 'JPN')
G.add_edge('BRA', 'MEX')
G.add_edge('BRA', 'MYS')
G.add_edge('BRA', 'NLD')

G.add_edge('CAN', 'USA')

G.add_edge('CHN', 'AUS')
G.add_edge('CHN', 'BRA')
G.add_edge('CHN', 'CAN')
G.add_edge('CHN', 'DEU')
G.add_edge('CHN', 'ESP')
G.add_edge('CHN', 'FRA')
G.add_edge('CHN', 'GBR')
G.add_edge('CHN', 'HKG')
G.add_edge('CHN', 'ITA')
G.add_edge('CHN', 'JPN')
G.add_edge('CHN', 'KOR')
G.add_edge('CHN', 'MEX')
G.add_edge('CHN', 'MYS')
G.add_edge('CHN', 'NLD')
G.add_edge('CHN', 'SGP')

G.add_edge('DEU', 'USA')
G.add_edge('DEU', 'BRA')
G.add_edge('DEU', 'CAN')
G.add_edge('DEU', 'ESP')
G.add_edge('DEU', 'ITA')
G.add_edge('DEU', 'MEX')

G.add_edge('ESP', 'USA')
G.add_edge('ESP', 'BRA')
G.add_edge('ESP', 'CAN')
G.add_edge('ESP', 'FRA')
G.add_edge('ESP', 'JPN')
G.add_edge('ESP', 'MEX')
G.add_edge('ESP', 'NLD')

G.add_edge('FRA', 'USA')
G.add_edge('FRA', 'BRA')
G.add_edge('FRA', 'CAN')
G.add_edge('FRA', 'DEU')
G.add_edge('FRA', 'GBR')
G.add_edge('FRA', 'JPN')
G.add_edge('FRA', 'MEX')
G.add_edge('FRA', 'NLD')

G.add_edge('GBR', 'USA')
G.add_edge('GBR', 'CAN')
G.add_edge('GBR', 'DEU')
G.add_edge('GBR', 'JPN')
G.add_edge('GBR', 'MEX')
G.add_edge('GBR', 'NLD')

G.add_edge('HKG', 'USA')
G.add_edge('HKG', 'AUS')
G.add_edge('HKG', 'BRA')
G.add_edge('HKG', 'CAN')
G.add_edge('HKG', 'DEU')
G.add_edge('HKG', 'ESP')
G.add_edge('HKG', 'FRA')
G.add_edge('HKG', 'GBR')
G.add_edge('HKG', 'ITA')
G.add_edge('HKG', 'JPN')
G.add_edge('HKG', 'KOR')
G.add_edge('HKG', 'MEX')
G.add_edge('HKG', 'MYS')
G.add_edge('HKG', 'NLD')
G.add_edge('HKG', 'SGP')

G.add_edge('ITA', 'USA')
G.add_edge('ITA', 'BRA')
G.add_edge('ITA', 'CAN')
G.add_edge('ITA', 'JPN')
G.add_edge('ITA', 'MEX')
G.add_edge('ITA', 'NLD')

G.add_edge('JPN', 'USA')
G.add_edge('JPN', 'CAN')
G.add_edge('JPN', 'DEU')
G.add_edge('JPN', 'KOR')
G.add_edge('JPN', 'MEX')
G.add_edge('JPN', 'NLD')

G.add_edge('KOR', 'USA')
G.add_edge('KOR', 'AUS')
G.add_edge('KOR', 'BRA')
G.add_edge('KOR', 'CAN')
G.add_edge('KOR', 'DEU')
G.add_edge('KOR', 'ESP')
G.add_edge('KOR', 'FRA')
G.add_edge('KOR', 'GBR')
G.add_edge('KOR', 'MEX')
G.add_edge('KOR', 'MYS')
G.add_edge('KOR', 'NLD')

G.add_edge('MEX', 'USA')

G.add_edge('MYS', 'USA')
G.add_edge('MYS', 'CAN')
G.add_edge('MYS', 'DEU')
G.add_edge('MYS', 'ESP')
G.add_edge('MYS', 'FRA')
G.add_edge('MYS', 'GBR')
G.add_edge('MYS', 'ITA')
G.add_edge('MYS', 'JPN')
G.add_edge('MYS', 'MEX')
G.add_edge('MYS', 'NLD')

G.add_edge('NLD', 'USA')
G.add_edge('NLD', 'CAN')
G.add_edge('NLD', 'DEU')
G.add_edge('NLD', 'MEX')

G.add_edge('SGP', 'USA')
G.add_edge('SGP', 'BRA')
G.add_edge('SGP', 'CAN')
G.add_edge('SGP', 'DEU')
G.add_edge('SGP', 'ESP')
G.add_edge('SGP', 'FRA')
G.add_edge('SGP', 'GBR')
G.add_edge('SGP', 'JPN')
G.add_edge('SGP', 'MEX')
G.add_edge('SGP', 'MYS')


"""
COMANDO DIBUJO
"""
nx.draw(G, with_labels=True, node_size=500, font_size=10)
plt.show()
